# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Compile Eleventy plz

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 23 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Checkout important-documents repo
      uses: actions/checkout@v2
      with:
        repository: scuttlebutt-eu/important-documents
        path: important-documents
    - name: Prepend front matter to all important-documents markdown files
      run: |
        for file in important-documents/*
        do
          sed -i.old '1s;^;---\ntags:\n  - important-documents\n---\n\n;' $file
        done
    - name: Copy important-documents markdown files to root
      run: cp important-documents/*.md ./
    - name: Build the static site
      run: npm install && npm run build
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site

